@startuml 
title "HealthcareService resource with its surrounding context R4"
skinparam classAttributeIconSize 0
skinparam roundcorner 5

class "Encounter" as Enc <<ENCOUNTER>> {
    An interaction between a patient and healthcare provider(s)
    for the purpose of providing healthcare service(s)
    or assessing the health status of a patient.
    ---
    serviceType 0..1 : CodeableConcept (ServiceType / SEBaseHSAVerksamhetVS (example))
    serviceProvider: Reference (Organization)
    location.location: Reference (Location)
}


class "SEBaseOrganization" as Org <<ORGANIZATION>> {
    A formally or informally recognized grouping of people
    or organizations formed for the purpose of achieving 
    some form of collective action.
    ---
    identifer[hsaid]: Identifier 
    identifier[organizationIdentifer]: Identifier
    type 0..* : CodeableConcept (SEBaseOrganizationTypeVS (example)) 
    partOf: Reference (Organization)
}

class "SEBaseHealthcareService" as HSvc <<HEALTHCARE_SERVICE>> {
    A single healthcare service or category of services
    that are provided by an organization at a location
    ---
    category 0..* : CodeableConcept (ServiceCategory (example) )
    type 0..* : CodeableConcept (ServiceType / SEBaseHSAVerksamhetVS (example))
    specialty 0..* : CodeableConcept (Practice Setting Code Value Set (preferred)) 
    location: Reference (Location)
    providedBy: Reference (Organization)
}

class "Location" as Loc <<LOCATION>> {
    A physical place where services are provided 
    and resources and participants may be stored, 
    found, contained, or accommodated.
    ---
    type 0..* : CodeableConcept (V3 Value SetServiceDeliveryLocationRoleType) (extensible)
    managingOrganization: Reference (Organization)
    partOf : Reference (Location)
}


Enc --> "0..1" Org : "serviceProvider.Reference"
HSvc --> "0..1" Org : "providedBy.Reference"
Org --> "0..1" Org : "partOf.Reference"
HSvc --> "0..*" Loc : "location.Reference"
Enc --> "0..1" Loc : "location.location.Reference"
Loc --> "0..1" Org : "managingOrganization.Reference"
Loc --> "0..1" Loc : "partOf.Reference"

footer Generated by PlantUML

legend
  Suggested CodeSystems from FHIR R4 are listed after coded elements
  with suggested binding in SE Base after the slash.
end legend

@enduml
