@startuml 
title "R4 - Organization and HealthcareService in Encounter "
skinparam classAttributeIconSize 0
skinparam roundcorner 5

class "Encounter" as Enc <<ENCOUNTER>> {
    An interaction between a patient and healthcare provider(s)
    for the purpose of providing healthcare service(s)
    or assessing the health status of a patient.
    ---
    serviceType : CodeableConcept (SEBaseHSAVerksamhetVS)
    serviceProvider: Reference (Organization)
    location.location: Reference(Location)
}


class "SEBaseOrganization" as Org <<ORGANIZATION>> {
    A formally or informally recognized grouping of people
    or organizations formed for the purpose of achieving 
    some form of collective action.
    ---
    identifer:hsaid: Identifier
    identifier:organizationIdentifer: Identifier
    type: CodeableConcept (SEBaseOrganizationTypeVS) 
    partOf : Reference(Organization)
}

class "SEBaseHealthcareService" as HSvc <<HEALTHCARE_SERVICE>> {
    a single healthcare service or category of services
    that are provided by an organization at a location
    ---
    category: CodeableConcept (ServiceCategory)
    type: CodeableConcept (SEBaseHSAVerksamhetVS)
    specialty: CodeableConcept (Practice Setting Code Value Set?) 
    location: Reference(Location)
    providedBy: Reference(Organization)
}

class "Location" as Loc <<LOCATION>> {
    information for a physical place where services 
    are provided and resources and participants may
    be stored, found, contained, or accommodated.
    ---
    type: CodeableConcept (ServiceType / MVO-kod)
    managingOrganization: Reference(Organization)
    partOf : Reference(Location)
}


Enc --> "0..1" Org : "serviceProvider.Reference"
HSvc --> "0..1" Org : "providedBy.Reference"
Org --> "0..1" Org : "partOf.Reference"
HSvc --> "0..*" Loc : "location.Reference"
Enc --> "1..1" Loc : "location.location.Reference"
Loc --> "0..1" Org : "managingOrganization.Reference"
Loc --> "0..1" Loc : "partOf.Reference"
footer Generated by PlantUML

@enduml
